-- 코드를 입력하세요
SELECT A.USER_ID, A.NICKNAME, 
CONCAT_WS(' ', CITY, STREET_ADDRESS1, STREET_ADDRESS2) AS 전체주소,
CONCAT_WS('-', LEFT(TLNO, 3), MID(TLNO, 4, 4), RIGHT(TLNO, 4)) AS 전화번호
FROM USED_GOODS_USER A
JOIN USED_GOODS_BOARD B
ON A.USER_ID = B.WRITER_ID
GROUP BY B.WRITER_ID
HAVING COUNT(*) >= 3
ORDER BY A.USER_ID DESC;